### ISSUE TITLE
How to install openmpi?

### ISSUE THREAD

**Issue by dragen1860** [tomgoldstein/loss-landscape#8]
Hi, thanks for your great job.
However, i found it's complex to install openmpi, could you give some simple instructions?

**Comment by seongkyun** [comment]
- go to https://www.open-mpi.org/software/ompi/v3.1/ and download `openmpi-3.1.2.tar.gz`
- `mkdir ~/openmpi` and move `openmpi-3.1.2.tar.gz` file to that folder
- `tar -zxvf openmpi-3.1.2.tar.gz` to unzip file
- `cd openmpi-3.1.2/`
- `./configure --prefix=$HOME/openmpi` to configure and compile
- `make -j8 all` to make (may taks 5~10min)
- `make install` to install
- `vim ~/.bashrc` to set the path
- add lines 
  - `export PATH=$HOME/openmpi/bin:$PATH`
  - `export LD_LIBRARY_PATH=$HOME/openmpi/lib:$LD_LIBRARY_PATH`
- save, exit and `source ~/.bashrc`
- `mpiexec --version` and `mpirun --version` to check the installation

its done
